### PR TITLE
[CIRC-8927]: (deploy/custom) Deployment manifest correctly references configmap key

### PR DESCRIPTION
**Pull request by aesca1er**
fix(deploy/custom): Deployment manifest correctly references configmap key

Fix custom deployment manifest to correctly reference configmap key

issue #CIRC-8927

* Tags: configmap deployment deploy/custom

### CODE REVIEW

**Review by maier — APPROVED** [review]
lgtm

**Review by dhaifley — CHANGES_REQUESTED** [review]
Is this PR outdated? It seems to include code changes from https://github.com/circonus-labs/circonus-kubernetes-agent/pull/100, but some of them seem to have been updated in that PR? Should they be combined? Should this PR be closed?

**Comment by aesca1er** [comment]
> Is this PR outdated? It seems to include code changes from #100, but some of them seem to have been updated in that PR? Should they be combined? Should this PR be closed?

I branched off of a feature branch twice -- not uncommon practice, but not what GitHub is expecting.
None of the PRs need to be closed.
As I merge the older PRs, the new ones will close in scope.

**Review by dhaifley — APPROVED** [review]
LGTM. Your changes to golangci-lint.yml and .golang.yml seem to be modified by later PR's that include these changes. But, other than that I think this looks good.

**Comment by aesca1er** [comment]
> LGTM. Your changes to golangci-lint.yml and .golang.yml seem to be modified by later PR's that include these changes. But, other than that I think this looks good.

That shows the correct history of progression.
Each branch maintains the ability to build under the constraints of what exists in the branch.
Build reproducibility is paramount to the reliability of the product.

**Pull request merged**
