### PR TITLE
[CIRC-8921]: Bump dependencies and go version

### PR DESCRIPTION
**Pull request by aesca1er**
Update dependencies
Update io/ioutil -> io and os
Update go version in go.mod

issue #CIRC-8921

Update dependencies and minimum required Go version (1.17)

* Tags: deps ioutil io os go version 1.17

### CODE REVIEW

**Review by maier — COMMENTED** [review]
99 appears to have both sets of changes

**Review by maier — APPROVED** [review]
lgtm

**Review by dhaifley — CHANGES_REQUESTED** [review]
I put my comments about this code on the other PR that seems to include these changes: https://github.com/circonus-labs/circonus-kubernetes-agent/pull/100. This PR looks to be a duplicate of that, but without vendoring the dependencies. Should this PR be closed since https://github.com/circonus-labs/circonus-kubernetes-agent/pull/100 includes these changes?

**Comment by aesca1er** [comment]
> I put my comments about this code on the other PR that seems to include these changes: #100. This PR looks to be a duplicate of that, but without vendoring the dependencies. Should this PR be closed since #100 includes these changes?

No.
As I merge the older PRs, the scope of the newer PRs will clear up.

**Review by dhaifley — APPROVED** [review]
LGTM

**Pull request merged**
